### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by kalpaj12**
`if (exec == 0)` then we need to break from the `while` loop, this fixes the segmentation core dump issue. I guess after ce969215b91de0ba0621ef83a102df187016ca3f is when this issue came up **[ We were still inside the while loop when exec is 0 ]**

### CODE REVIEW

**Comment by PawanKartikS** [comment]
Could you post the steps to reproduce the segfault?

**Comment by PawanKartikS** [comment]
Not merging this PR. Please fix the pending bugs.
Debug mode is printing out garbage values for stack (hint: you're calling `display()` twice). It is `display()` that frees up the stack, not `destroy_glob()`.

**Comment by PawanKartikS** [comment]
Please do not add anymore commits to this PR. I'm rolling out a commit - `destroy_glob()` frees up stack now, not `display()`.

**Comment by PawanKartikS** [comment]
737d73c fixes this issue.

**Comment by kalpaj12** [comment]
Ignore this PR, closing due to multiple conflicts

**Pull request closed without merging**
