### PR TITLE
Major revision to code

### LINKED ISSUE #26: Shows core dumped for memory.
I compiled a program
`MOV AL, 12`

and the results for memory broke. It shows
```
Memory:
free(): double free detected in tcache 2
[1]    23962 abort (core dumped)  ./ase test.asm --all-flags
```

Tried compiling it with and without flags and the issue persists.

### PR DESCRIPTION
**Pull request by kalpaj12**
1. Fixes #26 
2. Some code cleanup
3. Major bug fix when using debug mode

### CODE REVIEW

**Comment by PawanKartikS** [comment]
Does this fix the core dump issue? #26

**Comment by kalpaj12** [comment]
@mythio has to check

**Comment by PawanKartikS** [comment]
Let him check. I will merge on the confirmation.

**Comment by kalpaj12** [comment]
@mythio , clone my fork and test again. I guess the latest commit must have resolved the issue

**Comment by kalpaj12** [comment]
Accept PR

**Pull request merged**
