### PR TITLE
Code reformat

### PR DESCRIPTION
**Pull request by kalpaj12**
1. Code reformat
2. Debug mode added
Run debug mode via `./ase main.asm --all-flags -d`

### CODE REVIEW

**Comment by PawanKartikS** [comment]
Merged, but then reverted again. 2 reasons:
1. Debug mode doesn't work as expected. I thought that debug mode or stepping mode evaluates 1 line at a time. Yours doesn't seem to do that.

2. Mode `d` before `f` as - `ab:df..`.

**Comment by kalpaj12** [comment]
okay, I will make the necessity changes and send a PR again

**Comment by PawanKartikS** [comment]
I think you need to display the info before calling each `parse_line()` for debug mode.

**Comment by PawanKartikS** [comment]
> Moved `p_args.h` and `p_args.v` above `p_args.f`, so that when using multiple args, all are validated and displayed

Also, I don't think you need to move anything. Note that the args are validated in `main` and then passed to `display`. So the order is irr-relevant.

**Comment by kalpaj12** [comment]
`./ase main.asm --all-flags -v` Try running this.

**Comment by PawanKartikS** [comment]
That's actually another bug. Not related to this. It's because when you invoke `-v` without executing the source, `glob` remains uninitialized. Look at line 79

```c
if (!glob->mem->head) {
	return;
}
```

Since glob is `NULL` here, the function `display` quits, not giving a change for `-v` to execute.

**Comment by kalpaj12** [comment]
Screenshot from 2019-05-18 19-07-04

https://github.com/PawanKartikS/ASE/pull/16#issuecomment-493677126 is referenced `Evaluating instruction []` (attached screenshot)

**Comment by kalpaj12** [comment]
> That's actually another bug. Not related to this. It's because when you invoke `-v` without executing the source, `glob` remains uninitialized. Look at line 79
> 
> ```c
> if (!glob->mem->head) {
> 	return;
> }
> ```
> 
> Since glob is `NULL` here, the function `display` quits, not giving a change for `-v` to execute.

Oh, okay. Could you fix that, meanwhile, I'll try implementing line debug

**Comment by PawanKartikS** [comment]
I've already fixed it. See the reference.

**Comment by PawanKartikS** [comment]
> Screenshot from 2019-05-18 19-07-04
> 
> [#16 (comment)](https://github.com/PawanKartikS/ASE/pull/16#issuecomment-493677126) is referenced `Evaluating instruction []` (attached screenshot)

Could you explain this?

**Comment by kalpaj12** [comment]
> I think you need to display the info before calling each `parse_line()` for debug mode.

The screenshot is for this comment

**Comment by PawanKartikS** [comment]
Look at your debug movie. It's evaluating `AX` after `MOV` while it should be evaluating `MOV` after `ADD`.

**Pull request merged**
