### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by kalpaj12**
1. Range limits are modified to match maximum and minimum possible 16 bit representation of a decimal value.
2. This helps give a base foundation to work with negative values. **(Resolves most of the issues related to negative numbers)**

### CODE REVIEW

**Comment by PawanKartikS** [comment]
Why did you change the ranges?

**Comment by kalpaj12** [comment]
A 16-bit register can store 2^16 different values. The signed range of integer values that can be stored in 16 bits is −32,768  to 32,767 the unsigned range is 0 through 65,535.Since we are using signed rep, hence -32768 to 32767

**Comment by kalpaj12** [comment]
`c_dval = (int16_t)c_dval;`
and
`c_sval = (int16_t)c_sval;`
are casted to 16 bit integer representation. Previously `c_dval and  c_sval` were being assigned 65535 for 0xFFFF. Now, 0xFFFF it is treated as -1.

**Comment by PawanKartikS** [comment]
So this PR solves the issue with the negative numbers?

**Comment by kalpaj12** [comment]
Can you work on https://github.com/PawanKartikS/ASE/pull/14#issuecomment-493254515 and https://github.com/PawanKartikS/ASE/pull/14#issuecomment-493254515 ?

**Comment by kalpaj12** [comment]
I don't think there is any necessity to make changes to `mem.c` and `glob.c` (Refering to: https://github.com/PawanKartikS/ASE/pull/14#issuecomment-493254515 to change other variables to 16bit int).

Also, can you add the closed issue's code in unit tests? [Opening a separate issue for now.]

**Comment by PawanKartikS** [comment]
1. There's a slight problem. Registers should show only 4 hex bits. After you've made changes to the size of int, registers now show more than 4 bits. Masking or padding them to 4 bits may cause data loss.
2. Yes, I will do that.

**Comment by kalpaj12** [comment]
Could you provide an example code for data loss?

**Comment by PawanKartikS** [comment]
Never mind, I think I may have fixed it. See this commit f09ce75. I think this also fixes the DX issue.

**Pull request merged**
